name: Deploy Pre-built Runtime

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Mo.PersonalWebsite/Mo.PersonalWebsite.csproj
      
    - name: Build and publish
      run: dotnet publish src/Mo.PersonalWebsite/Mo.PersonalWebsite.csproj -c Release -o src/Mo.PersonalWebsite/publish
      
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 188.245.247.13 >> ~/.ssh/known_hosts
        
        # Configure SSH to prevent timeouts
        cat >> ~/.ssh/config << EOF
        Host 188.245.247.13
          ServerAliveInterval 60
          ServerAliveCountMax 3
        EOF
        
    - name: Deploy to server
      run: |
        # Copy entire repository including the publish folder
        rsync -avz --delete ./ root@188.245.247.13:/root/mowebsite/
        
        # Deploy using the main docker-compose file with GitHub secrets as environment variables
        ssh root@188.245.247.13 "
          cd /root/mowebsite/deployment &&
          docker-compose down &&
          WEBAPP_PORT=${{ secrets.WEBAPP_PORT }} \
          ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} \
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
          SQL_SERVER_PASSWORD=${{ secrets.SQL_SERVER_PASSWORD }} \
          ENVIRONMENT=prod \
          ASPNETCORE_ENVIRONMENT=Production \
          DATABASE_NAME=MoPersonalWebsite_Prod \
          docker-compose up --build -d
        "